### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by ghost** [savoirtech/aetos#2]
The `README.md` provides some brief instructions for how to start Aetos, but the package doesn't ship with a `bin/` directory, so some build instructions are also necessary.  Could that also be added to the `README`?

**Comment by jgoodyear** [comment]
Thanks for the question, I'll update the Readme.md shortly.

**Comment by jgoodyear** [comment]
Hi, 

We've updated the ReadMe.md:
https://github.com/savoirtech/aetos/blob/master/README.md

Please download or build locally from source the Aetos Integration Platform. Extract tar.gz or zip distribution file, you'll find the bin folder inside.

Thank you for posting your question, please let us know if there are any other improvements we can make.

**Comment by ghost** [comment]
Excellent, thanks for the update.
